### ISSUE TITLE
[Bug]: Game crashes as soon as I click play on minecraft launcher (linux)

### ISSUE THREAD

**Issue by xMicky24GIT** [FTBTeam/FTB-App-Feedback#43]
### Modpack

FTB OceanBlock

### Modpack version

1.2.0

### Log Files

I can't find logs, only a message saying "Game crashed" and "Exit Code: 0"

### Describe the bug

The game crashes when I launch it. I'm on Arch Linux, I just downloaded the FTBApp and FTB Ocean Block

### Steps to reproduce

1. Open FTBApp
2. Click Play on FTB OceanBlock
3. Click play on the minecraft launcher
4. Game crashes instantly

### Expected behaviour

Modpack starting

### Screenshots

![image](https://user-images.githubusercontent.com/31669768/135471726-048fc94c-e6b2-410e-a923-779ec0aa9795.png)

**Comment by xMicky24GIT** [comment]
I tried with multimc5 now, the game starts loading but crashes before showing the main menu.
This is the Minecraft log I get from multimc https://paste.feed-the-beast.com/view/c408eff5

**Comment by xMicky24GIT** [comment]
I was using java 16 instead of java 8. Now it's working on multimc but still the same crash when launching with ftbapp

**Comment by Noobprototype** [comment]
Same for me and I'm on mac

**Comment by Raidobw2** [comment]
For Linux: Can you check in `~/.ftba/logs/latest.log` for a group of words like "Didn't find Launch Mod". Maybe by doing a `grep` with the word "Launch" could quickly tell that.

For MacOS: Same thing but the location is `~/Library/Application Support/.ftba/logs/latest.log` instead.

If this is within that log file, it means Forge didn't install properly. You can then look up how to fix that at <https://www.notion.so/feedthebeast/Manually-installing-Forge-into-the-FTB-App-d0473bbea1aa43d6ae3830bea686bc13> to install it manually as a workaround.

Important to let us know if that was the case in the logs and if using the workaround patched it properly in that case, since it's been a problem with the automated Forge installs that we have noticed.

**Comment by Noobprototype** [comment]
THANKS!!!!

**Comment by xMicky24GIT** [comment]
> For Linux: Can you check in `~/.ftba/logs/latest.log` for a group of words like "Didn't find Launch Mod". Maybe by doing a `grep` with the word "Launch" could quickly tell that.
> 
> For MacOS: Same thing but the location is `~/Library/Application Support/.ftba/logs/latest.log` instead.
> 
> If this is within that log file, it means Forge didn't install properly. You can then look up how to fix that at https://www.notion.so/feedthebeast/Manually-installing-Forge-into-the-FTB-App-d0473bbea1aa43d6ae3830bea686bc13 to install it manually as a workaround.
> 
> Important to let us know if that was the case in the logs and if using the workaround patched it properly in that case, since it's been a problem with the automated Forge installs that we have noticed.

Yup, that was the problem. The workaround fixed it.

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
