### ISSUE TITLE
App crashes if left open when putting PC to sleep

### ISSUE THREAD

**Issue by fruitshakes** [FTBTeam/FTB-App-Feedback#56]
### What Operating System

Windows 10

### App Version

202110071354-4bdfd15050-release

### UI Version

4bdfd15050

### Debug Code

FTB-DBGSEWAKIHEBE

### Describe the bug

If I leave the app open when putting PC to sleep, I come back to a 'Oh... This is a bit awkward It looks like something has gone wrong with the App.' screen

### Steps to reproduce

1. Open app
2. Put PC to sleep
3. Come back (next day in my case) and log in
4. Error screen should show

### Expected behaviour

No error screen

### Screenshots

![Overwolf_2021-10-12_18-15-07](https://user-images.githubusercontent.com/5645729/137001187-09d64b0f-c184-4c1e-9841-d337f7ab36d9.png)

### Additional information

It's actually Windows 11, but it wasn't an option in the dropdown

**Comment by Jaylow7** [comment]
I am also experiencing this crash. Windows 10 64-bit

**Comment by ecatherman** [comment]
I also get this crash on Windows 10.

app version: 202111101147-418dcf2f3b-release
UI version: 418dcf2f3b

**Comment by vorinia** [comment]
Happening to me also. Windows 10 64-bit, Ryzen 5, 16GB RAM. Has been happening for at least 3 weeks now, but I've never taken the time to search for the issue prior to today.

Minecraft itself is fine, and will allow a continuation of any game, but the FTB App requires a restart.

**Comment by SonicNico** [comment]
I also have this problem.

**Comment by noelbenz** [comment]
Having the same problem. In the bottom left I see:

![image](https://user-images.githubusercontent.com/897094/147708657-825316e1-9fc8-4fac-9e84-74a0d0bee131.png)

The reconnect increments every roughly 5 seconds.

background.html.log: https://pastebin.com/X6Y5C43H
index.html.log: https://pastebin.com/1D6cBJuN

It looks like the background service shutsdown when the computer is woken up:

`2021-12-29 16:33:13,257 (INFO) </dist/background/main.js> (:28) - [22:33:12] [pool-2-thread-1/ERROR] [FTB Subprocess]: Closed backend due to websocket error! Also no messages from frontend for 12 seconds.`

And the frontend just tries to reconnect indefinitely.

**Comment by MichaelHillcox** [comment]
Added to main list of launch issues #119 thanks for your help by reporting your issue, we're looking into it :+1:
