### ISSUE TITLE
FTB App Break the CurseForge Launcher

### ISSUE THREAD

**Issue by Rey-Sol** [FTBTeam/FTB-App-Feedback#57]
### What Operating System

Windows 10

### App Version

202110071354-4bdfd15050-release

### UI Version

4bdfd15050

### Log Files

https://pste.ch/japaloceve

### Debug Code

FTB-DBGLAMORAPUYI

### Describe the bug

The launcher mess how Curse Forge  handle mod launching. When you try to open a game with CurseForge it open the last FTB app Modpack instead

### Steps to reproduce

1) Install the CurseForge mod launcher
2) Install a modpack with CurseForge
3) Launch the modpack installed with CurseForge
4) Exit the game
5) Install the FTB App
6) Install an other  modpack with the FTB App 
7) Launch the FTB modpack
8) exit
9) try to launch  the CurseForge modpack
10) you should see the FTB modpack in the launch game window

### Expected behaviour

The FTB app should not overwrite the settings of CurseForge launcher.

### Screenshots

![ftb_ocean issue](https://user-images.githubusercontent.com/81772757/137005515-3a226e97-1c3a-497d-9658-8aa21fd403f5.PNG)

**Comment by MichaelHillcox** [comment]
This isn't possible. My assumption here is that you already had the mc launcher open in the background, upon clicking play, it re-opened this version instead of our own / their own and caused this to happen. Our app tries to close any existing Mc launcher instances but others might not. Please ensure you have closed all instances of the mc launcher before trying to play a pack :+1:
