### ISSUE TITLE
Empty modpack screen in "Library" tab

### ISSUE THREAD

**Issue by spaceshooter** [FTBTeam/FTB-App-Feedback#95]
### What Operating System

Linux (Debian)

### App Version

202111051727-fc8797cf31-release

### UI Version

fc8797cf31

### Debug Code

FTB-DBGOREMEDEJOY

### Describe the bug

Any modpack screen is completely empty

### Steps to reproduce

1. Go to "Library" tab
2. Try to open any installed pack
3. Followed screen is absolutely empty

### Expected behaviour

Expected to see at least "Play" button there

### Screenshots

![image](https://user-images.githubusercontent.com/49607410/143729844-38f2e374-d099-4be9-9911-6bcb149ba9ce.png)
![image](https://user-images.githubusercontent.com/49607410/143729965-3788802e-04d2-4d79-8a2c-4a73b7063646.png)

### Additional information

Distro: KDE Neon 5.23

**Comment by IAmalchemy2** [comment]
i have also run into this with my app none of the installed packs show anything when clicked on but still launch

**Comment by MichaelHillcox** [comment]
Hay, sorry for not responding sooner, this should be fixed in the next release, we're looking at somewhere near the middle of Decemember for the next release. Thank you everyone that has submitted infomation here!

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install, pack launch system, and we no longer use the Minecraft Launcher. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: `bdf8bdbaca`, subprocess: `202112101445-bdf8bdbaca-release`.
